[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#glam = "0.29.2"
itertools = "0.14.0"
#nom = "7.1.3"
#nom_locate = "4.2.0"
colored = "3.0.0"
regex = "1.11.1"
rayon = "1.10.0"
aocutils = { path = "../aocutils" }
plotters = "0.3.7"

# egui
eframe = {version = "0.31.0", features = [
    "default",
    "__screenshot", # __screenshot is so we can dump a screenshot using EFRAME_SCREENSHOT_TO
] }
# For image support:
egui_extras = {version = "0.31.0", features = ["default", "image"] }
env_logger = { version = "0.11.6", default-features = false, features = [
    "auto-color",
    "humantime",
] }

#[[example]]
#name = "ferris"