[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#glam = "0.29.2"
itertools = "0.13.0"
#nom = "7.1.3"
#nom_locate = "4.2.0"
colored = "2.2.0"
regex = "1.11.1"
rayon = "1.10.0"
aocutils = { path = "../aocutils" }
